# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpAssessmentQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('issuing_rto', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('certificate_number', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpVocationalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpVocationQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='trainer.TrainerIntroduction')),
            ],
        ),
        migrations.AddField(
            model_name='expvocationqualification',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.TrainerWorkExperience'),
        ),
        migrations.AddField(
            model_name='expassessmentqualification',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.TrainerWorkExperience'),
        ),
    ]
