# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170830_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('RTO', 'RTO')], default='Trainer', max_length=50),
        ),
    ]
