# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
